### ISSUE TITLE
Рефакторинг групповых чатов

### ISSUE THREAD

**Issue by schubarkrsk** [schubarkrsk/classmates_webapp#3]
# TODO: Натан, какая то херня с моделями
"""

- [x] Регистрация групповых чатов (GroupChat)

id - AutoField
owner - ForeginKey для timetable_model.Users
title - VarcharField (название чата)

- [x] Члены группового чата

id - AutoField
chat - ForeginKey для GroupChat
user_id - ForeginKey для timetable_model.Users

- [x] Сообщения в групповом чате

id - AutoField
chat - ForeginKey для GroupChat
user_id - ForeginKey для timetable_model.Users
date - DateField
time - TimeField
message - TextField
"""
